### ISSUE TITLE
How do we send the alerts?

### ISSUE THREAD

**Issue by SimonSterckxx** [SimonSterckxx/AIApplications#4]
Do we just show an alert on the interface like we do now, on the video itself, a pop-up or make it send a message to an email?

**Comment by despallier** [comment]
In this workshop you do not have to focus about the communication aspects. First try to implement an algorithm that detects people in the need of help. After all, this course is about AI (using AI models for inderence, training our own designed AI architectures etc) ...and less about informatics.( sending emails from a python program).
